# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: skuriyam <skuriyam@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/03 21:58:08 by skuriyam          #+#    #+#              #
#    Updated: 2025/11/06 19:34:11 by skuriyam         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= libftprintf.a
cc	= cc
CFLAGS	=	-Wall -Wextra -Werror
AR	= ar rcs


SRCS	=	ft_printf.c ft_put_hex_x.c ft_put_hex_ul.c ft_putchar.c ft_putnbr.c \
			ft_putstr.c ft_putunbr.cc

OBJS	$(SRCS:.c=.o)

$(NAME): $(OBJS)
	
		
		
